# node image for developing vuejs project
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    image: vuejs-test:dev
    container_name: vuejs
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: npm run serve